version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t diabetes-ml-api .
      - docker tag diabetes-ml-api:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/diabetes-ml-api:latest

  post_build:
    commands:
      - echo Pushing image to ECR
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/diabetes-ml-api:latest
